### PR TITLE
Remove committed libraries from the repository

### PR DESCRIPTION
**Pull request by Sanne**
Removes both the /lib directory and the .idea project metadata.

The jars you need for integration tests are copied automatically in a new phase which is a precondition to run tests.

I've also changed the name from `/lib` to `/test-runtime-libs` to avoid confusion, as it's not copying all of the project dependencies, just the test runtime dependencies.

### CODE REVIEW

**Comment by Sanne** [comment]
well the patch looks like large but if you ignore the deleted files it's just a couple of lines :)

**Comment by gavinking** [comment]
Why would you delete the IntelliJ metadata?

**Comment by Sanne** [comment]
> Why would you delete the IntelliJ metadata?

We never commit those typically? They contain machine specific data, often also specific to the version of the IDE, the path of your tools, the custom plugins one has installed.

IDEA recognizes the project as a Gradle project, you can just import it the standard way and shouldn't need any further steps? Or am I missing something odd you might have made to work on the annotation processor?

**Comment by gavinking** [comment]
The only file that is machine-specific is `workspace.xml` and the usually practice is to `.gitignore` that one. All the rest are common. I have never once seen IntelliJ community correctly import a Gradle project IRL. In particular it failed completely when I attempted to import `hibernate-orm` a couple of days ago.

**Comment by sebersole** [comment]
FWIW It only fails if you do not run compile first.  The reason being that
it needs to run its code generators.  Such an expectation is not atypical
in my experience.  And even if you pulled an existing IJ config, it still
would not work until you completed that step.

**Comment by gavinking** [comment]
OK, but the issue is that building the whole of the project takes a very long time. If I’m not mistaken, the only thing in `hibernate-core` that depends on a Gradle build is the generated source, and I don’t need it if all I want to do is open up the project and look around. And if I want to generate source I just run `gradle hibernate-core:compileJava`, I don’t need to build everything else. At least I don’t think I do, do I?

**Comment by sebersole** [comment]
Well first we are talking about query-validator here not orm ;)  But you
mentioned orm so I thought I'd reply to that comment.  I have noticed that
lately compiling test sources does take quite a long time.  But the problem
with not compiling is that annotation processors (ah, my fav) only kick in
with compilation.  Ideally we'd have IntelliJ run these steps as part of
importing.  There is a way to get close to that, but it does not quite work
in our specific case.

I think Sanne's point is that as a group we have decided to not push IDE
specific files.

**Comment by sebersole** [comment]
I should have said up-front that it depends what you mean by "the import
does not work".  "Does not work" always kind of needs qualification ;)

If you mean the import fails, well that's never been my experience.  Andrea
and I import these all the time.
If you mean that after import the project "does not compile", well see my
previous comments.  But that is not how I would interpret "open up the
project and look around".

If you explain more what happens in importing orm we can try to help you.
Here is not the right place for that though

**Comment by Sanne** [comment]
> The only file that is machine-specific is workspace.xml and the usually practice is to .gitignore that one. 

No strong feelings, if you want to keep it I can amend my PR - but I'm surprised, I've never seen any project doing that, it's always been a rule to not commit any IDE metadata file in all projects I've worked on.

> I have never once seen IntelliJ community correctly import a Gradle project IRL

Just wondering, did you try it? I imported this project just fine, so I'd just go with it.

**Comment by gavinking** [comment]
> Just wondering, did you try it? I imported this project just fine, so I'd just go with it.

So I just tried it. Here's what I did:

1. Checked out your branch
2. Used `git status` to ensure I had a clean workspace
3. Deleted the `.idea` director
3. Ran `./gradlew ` from the command line, successful build
4. Used 'Import Project', 'Import project from external model' ('Gradle') to import the project into IntelliJ

The result:

- The project's source and resource directories were not detected by IntelliJ, and I had to set them up explicitly.
- The Project SDK (Java 1.8) had to be explicitly set.
- None of the dependencies in `test-runtime-libs` were added to the classpath and I had to add them explicitly.
- IntelliJ complained that I had not set an output path.
- I realized that for some reason the dependency to JUnit was missing and then realized that the only dependency that had been picked up from the gradle build was ANTLR.
- I got some strange build error probably due to something wrong in the project output paths or who knows what.
- I gave up.

Did I do something wrong here? Was I supposed to use something other than 'Import Project' to import the project?

Like I said, I've never once seen this work. There must be something wrong with *me* because you guys all assure me it works perfectly. @Sanne?

¯\\_(ツ)_/¯

**Comment by Sanne** [comment]
I honestly don't know, but fine: I shouldn't have removed those metadata files, especially not in an unrelated commit.

I've amended the commit to specifically just remove the libraries, and have them fetched by Gradle.

Be warned that you should regenerate the IDEA metadata files, as the currently committed ones are not honoring the content of the build script, and will keep using the libraries you have used initially.

**Comment by gavinking** [comment]
> I honestly don't know, but fine

Note that one of the things that could happen is: if you test project import from gradle metadata without first nuking your `.idea` metadata directory (which of course you have added to `.gitignore`), everything would look like it works from, but then for a clean `git clone` it might not.

Anyway, I will re-retest when I get a spare moment, after we get the gradle build issues sorted.

**Comment by gavinking** [comment]
Thanks @Sanne, merged. And it let me get rid of a number of IntelliJ metadata files that ya'll hate so much.

**Comment by gavinking** [comment]
> Did I do something wrong here? Was I supposed to use something other than 'Import Project' to import the project?

OK, I think I might have tracked down the problem. (Or at least found part of it.) There an NPE from this line of `build.gradle`:

    compile files(Jvm.current().toolsJar)

Probably because by default IntelliJ is using a later version of the JDK than the one that `query-validator` targets. Without the metadata about which SDK to use, the initial gradle build simply fails and the project import stops.

So yeah, it *is* me. (And anyone else who has multiple JDKs set up.)

**Pull request merged**
